Reorganize some of the calls

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -16,6 +16,11 @@ setup() {
     return 1
   fi
 
+  if ! setup_base_software; then
+    logError "Failed to setup base software"
+    return 1
+  fi
+
   if ! setup_dev; then
     logError "Failed to setup developer environment"
     return 1
@@ -73,18 +78,6 @@ setup_dev() {
     return 1
   fi
 
-  # Install Librewolf
-  if ! librewolf_install; then
-    logError "Failed to install Librewolf"
-    return 1
-  fi
-
-  # Configure Librewolf for multi-profiles and Firefox Sync
-  if ! librewolf_configure; then
-    logError "Failed to configure Librewolf"
-    return 1
-  fi
-
   # Install Docker Desktop
   if ! docker_install "${BAAL_ROOT}/.config/local.env"; then
     logError "Failed to install Docker Desktop"
@@ -96,18 +89,6 @@ setup_dev() {
   #   logError "Failed to install VS Code"
   #   return 1
   # fi
-
-  # # Install baal tools globally
-  # if ! install_tools; then
-  #   logError "Failed to install baal tools"
-  #   return 1
-  # fi
-
-  # Install Android development tools
-  if ! android_install; then
-    logError "Failed to install Android development tools"
-    return 1
-  fi
 
   logInfo "Dev environment setup successfully"
   return 0
@@ -137,6 +118,34 @@ setup_dependencies() {
     logInfo "Failed to configure age"
     return 1
   fi
+
+  return 0
+}
+
+setup_base_software() {
+  # Install Librewolf
+  if ! librewolf_install; then
+    logError "Failed to install Librewolf"
+    return 1
+  fi
+
+  # Configure Librewolf for multi-profiles and Firefox Sync
+  if ! librewolf_configure; then
+    logError "Failed to configure Librewolf"
+    return 1
+  fi
+
+  # Install Android development tools
+  if ! android_install; then
+    logError "Failed to install Android development tools"
+    return 1
+  fi
+
+  # # Install baal tools globally
+  # if ! install_tools; then
+  #   logError "Failed to install baal tools"
+  #   return 1
+  # fi
 
   return 0
 }
